### ISSUE TITLE
Construction impossible if material on top of blueprint.

### ISSUE THREAD

**Issue by AlexanderEsin** [RocketJumpTechnology/King-under-the-Mountain-Issue-Tracking#13]
Essentially, if a blueprint for a build (e.g. table) is placed in a spot already committed for deposit of a material (e.g. ore) then the material will sit on top of the blueprint. Dwarves appear to get stuck in a loop (for several iterations) carrying materials necessary for blueprint (see image), but unable to deposit them. In some ways this is similar to #11 and #9 - but the raw material on the blueprint also becomes non-actionable. The dwarves won't process raw material deposited in this way (e.g. see attached image - the logs will not be carried for crafting into planks) or indeed move it if it's no longer in the stockpile zone as they usually would (you can also see that from the image). I have also reproduced this with rough boulders on a table blueprint.

In the image you should just be able to make out the grey outline of the blueprint under the dwarves trying to build it.

As far as I can tell there is no way to remove a blueprint (which may be the easiest short-term way of fixing it)?
![unbuildable_table_unmoveable_wood](https://cloud.githubusercontent.com/assets/15325436/24073230/3069cba0-0bec-11e7-8f91-a4d814688070.png)

**Comment by rossturner** [comment]
Thanks Alex, the fix for #11 should also fix this, but yes you're right that cancelling the blueprint would be a good temporary solution, which we planned to have in this release but had to be cut at the last minute due to far too many time constraints. Much appreciated!

**Comment by rossturner** [comment]
Finally around to new development and fixing issues - the game now tracks better which items belong to a construction blueprint (or not) and the dwarves move them out of the way first, so this shouldn't be an issue anymore.

**Comment by rossturner** [comment]
Think I'll leave this open until you can also cancel constructions, which should be in the next proper update as well.

**Comment by rossturner** [comment]
Fixed now :D

**Comment by AlexanderEsin** [comment]
First of all - so happy to see the progress etc! Finally getting around to trying the new build, but still struggling to remove blueprints / items. Presumably this is done with the "Orders -> Remove" tool, but it seems to be non-functional for me:

The mouse icon appears, yet I can't drag-select or click-select anything with it. I may well be missing something obvious, in which case I'm sorry! Platform is winx64

-AE

**Comment by rossturner** [comment]
Ah I guess I've been a bit too quick to close this from a release point of view - it's fixed in my current working build but wasn't yet released in the build that was put out 1st February (it'll be in the one on 1st March).

In that build you can (finally) click on constructions/blueprints and get an option to remove them, as well as the same for furniture and doors that have been built. In the future I should wait to close things until the fixes for issues have gone public. Thanks for investigating it :)

**Comment by rossturner** [comment]
Fixed in pre-alpha 2 being released to Patreon on March 1st
