### ISSUE TITLE
Cannot build stockpile furniture in stockpile zone

### ISSUE THREAD

**Issue by AlexanderEsin** [RocketJumpTechnology/King-under-the-Mountain-Issue-Tracking#16]
Hi Ross,

Title says it all I guess. If the stockpile is is intended to be unbuildable, then the furniture tab within the zone is misleading!

Attached image shows inability to place blueprint.

<a href="https://ibb.co/mcHDt7"><img src="https://preview.ibb.co/jTqYt7/Build_In_Stockpile_Zone.png" alt="Build_In_Stockpile_Zone" border="0"></a>

Best,

AE

**Comment by rossturner** [comment]
Oh great spot, I put something in to diallow furniture in a stockpile so I should have removed the option from the UI too. Will get this in my short term backlog to fix, thanks!

**Comment by rossturner** [comment]
Fixed in pre-alpha 2 being released to Patreon on March 1st
