### ISSUE TITLE
Resource number not corresponding to image

### ISSUE THREAD

**Issue by AlexanderEsin** [RocketJumpTechnology/King-under-the-Mountain-Issue-Tracking#17]
Hi Ross,

Screenshot attached. Just realised this might simply be due to there not being a 2-block image asset?

<a href="https://ibb.co/mxK7mS"><img src="https://preview.ibb.co/cLMbfn/Resource_Number_Vs_Image.png" alt="Resource_Number_Vs_Image" border="0"></a>

**Comment by rossturner** [comment]
This one's a working as intended, as yes there isn't a 2-block image asset. It'd be easy to mod in, though for now each pile of resources only has a set of (I think) 4 different images to represent 1 anywhere up to (currently) a quantity of 32. I think the rest look okay but the case of a quantity of 2 doesn't look quite right with a single block or 3.

Don't let this put you off raising issues though, they're extremely useful and it's also a big help to get a different perspective. Thanks Alex!

**Comment by rossturner** [comment]
FYI this isn't due to a technical constraint, the game can easily support as many different images for different amounts in a pile as required, it's just due to budget constraints and not having an artist on hand :)
