### ISSUE TITLE
Map inaccessibility - River (Can't build bridges)

### ISSUE THREAD

**Issue by AlexanderEsin** [RocketJumpTechnology/King-under-the-Mountain-Issue-Tracking#19]
Created a game instance where the river completely bisects the world map. Given the dwarves' unwillingness / inability to swim and no way of (yet) producing a bridge, any water connecting two map edges cuts the available map area down. In my case, this reduced the playable map to about 10%.

In the long run, this won't be an issue with bridges etc, but perhaps a short term solution is to have the dwarves start on the largest contiguous landmass?

Best,

Alex

**Comment by rossturner** [comment]
Great point on both counts - yes the intention is bridges would be in very soon so it's not too much of an issue, but also yes I should have updated the code that picks the starting point to pick the larger of the potential areas.

**Comment by rossturner** [comment]
This didn't make it into the pre-alpha 2 release :(

**Comment by rossturner** [comment]
Finally done in Alpha 1!
