### ISSUE TITLE
Message type 310

### ISSUE THREAD

**Issue by AlexanderEsin** [RocketJumpTechnology/King-under-the-Mountain-Issue-Tracking#20]
Morning Ross,

Left the game running overnight - and it seems fine, but the terminal (from which I launched the jar) output is now being flooded by
```
Message type 310 not handled
```
at a rate of 3-5 messages a second (on the fastest game setting - decreasing game speed decreases message output rate). I can't see anything explicitly wrong with the game itself. Quitting to menu pauses the error output, but resumes on "continue game". It's unhappy with something, but no idea what that is...

Best,

Alex

P.S. Starting a new game stopped the message output.

**Comment by rossturner** [comment]
Oh that's very useful, thank you! At least it survived being ran overnight :)

The game uses a simple publish/subscribe messaging model for most of the events in the game, using integers to denote what kind of event it is for efficiency. 310 is when an entity changes position (into a different cell) and it looks like it would be unhandled if either the tile or entity couldn't be found.

My best guess is that a character got stuck off the edge of the map, which is an existing issue I need to fix. I'll leave this one open to try and make sure that's the case and it's not something else, but it is a problem that occurs in long-running games (somehow) so I'm fairly confident it's this and not some other, unknown issue.

**Comment by AlexanderEsin** [comment]
> that a character got stuck off the edge of the map

That makes a lot of sense, given that cell calls will be made more frequently at higher game speeds

> but it is a problem that occurs in long-running games (somehow)

I've noticed that the longer the game, the further afield the dwarves tend to roam. Is that intended behaviour?

**Comment by rossturner** [comment]
It's not intended, the dwarves pick somewhere nearby to randomly move to, but I've accidentally weighted it slightly in two directions, so over a very long time they eventually congregate in a corner. Interesting but unintended. When there's a bit more going on in the game they'll hang around social areas and zones defined by the player.

**Comment by AlexanderEsin** [comment]
Ah I see!

> When there's a bit more going on in the game they'll hang around social areas and zones defined by the player.

Very cool!

**Comment by rossturner** [comment]
I've just been playing around with (and hopefully fixing) when characters get forced off the edge of the map, but this isn't causing the message type 310  unhandled error, though I did see some in the logs before I started investigating it properly, so this may be a different issue than characters falling off the edge of the world

**Comment by AlexanderEsin** [comment]
I'll keep an eye out for it - I'll have the Mac version run on my work machine over the weekend again and see if I can pinpoint the cause

**Comment by rossturner** [comment]
Thanks Alex :)

**Comment by rossturner** [comment]
Fairly certain this was caused due to state being held between different game worlds being generated which is fixed now
