### ISSUE TITLE
Wall building stall

### ISSUE THREAD

**Issue by AlexanderEsin** [RocketJumpTechnology/King-under-the-Mountain-Issue-Tracking#21]
Encountered a wall building stall than you can see in the linked video - the left and bottom segments of the quad (built using straight lines, rather than the quad tool if that makes any difference).

[Wall Stall](http://sendvid.com/4zhuxitb)

I proceeded to build the extra straight lines around the place to see whether this would re-ignite the quad construction (to no avail as you can see). The furthest right wall suffers a stall as I run out of ingredients, but mining and processing some more allows it to be finished. The only error codes that appeared around the time of the quad stalling construction (I wasn't keeping very accurate track of timing) were the follows:

```More construction ingredients than tile locations - the construction recipe should be simplified to use fewer ingredients or cover more tiles```

The error appears approximately the same number of times as there are blocks missing from the incomplete wall segments. Here I'm counting as a segment blueprint with 1 ingredient as missing 2 ingredients, and so on...

Best,

Alex

P.S. presumably being able to remove the blueprint in the next allows to manually mitigate the gameplay aspect of having incomplete walls :)

**Comment by rossturner** [comment]
Ah that's good to know as I didn't think this would happen anymore - unlike earlier versions the walls will now pick a specific material to use in their construction (as compared to say, both marble and dolostone) and that error message is when multiple different materials have been picked but they can't both go into the same tile. 

You're right that you should be able to cancel these in the next build, while not ideal would be a workaround, but I need to stop this from happening too. Thanks again!

**Comment by rossturner** [comment]
Pretty sure this doesn't happen anymore
