### ISSUE TITLE
Breaking down wooden walls

### ISSUE THREAD

**Issue by AlexanderEsin** [RocketJumpTechnology/King-under-the-Mountain-Issue-Tracking#22]
Hi again Ross,

Great job on the release! A small thing I noticed with the wooden walls is that the command to remove them is "Mine" - same as with the stone walls. They are broken down by carpenters (I checked :) ), so presumably should be "Chopped"?

All the best,

Alex

**Comment by rossturner** [comment]
Thanks Alex and good spot! While it is a bit odd that mine will remove constructed walls, I didn't want to have to make the player select a different command for different types of wall to be removed. "Remove walls" doesn't quite feel right to me when the primary use is mining so I'm not sure how to change it yet, other than that I don't want it to be a pain for the player to remove natural rock, wooden walls, stone walls etc.

**Comment by rossturner** [comment]
Moved to https://trello.com/c/r5lbf3Em
