### ISSUE TITLE
Suggestion: Protect Resources

### ISSUE THREAD

**Issue by AlexanderEsin** [RocketJumpTechnology/King-under-the-Mountain-Issue-Tracking#23]
With the addition of trees seeding other trees (nice job btw - I like how the smaller trees give fewer logs) it would be nice to be able to sustainably manage the trees. My approach typically is to square-select areas to chop, clear etc... However, in a given area it would be nice to keep adult trees to reseed - especially if the tree-type is sparse.

How about giving the player an ability to "protect" a certain set of resources. It could be selected like the other commands and perhaps leave a small shield icon over the resources to which it was assigned (translucent like the chop icon). The protected status would essentially subtract those resources from a "clear"- type command such as mine/chop/clear. This would allow players to efficiently clear large areas without having to manually select around resources they wish to keep. The protect status should remain until removed (e.g. with the existing remove command).

As an aside, it would also be a neat way to easily leave natural rock walls when mining into large areas; meaning players can map out structures within the rock in advance and have dwarves remove everything else!

Alex

**Comment by rossturner** [comment]
Yep clearing a large area isn't a good approach for sustaining trees for growth in an area, it's more effective to take out strips of a wood and let them grow back in again.

My intention is to add in the ability to sometimes find seeds when chopping down trees, and be able to give these to a forrester to plant new trees where the player wants. This would be similar to the inspiration of _The Settlers_ and its method of growing and chopping down trees. I was also thinking to disallow this ability from dwarves and instead only allow them to farm large tree-like mushrooms underground which give (effectively) logs to use as planks. 

I think when I get farming in (which really is coming over the horizon!) I'll also add in growing trees, potentially regardless of having seeds. 

So for your suggestion is it just trees that you'd want this for currently? Although I can see players wanting to not remove bushes that grow fruit while clearing out other ones. 

Also for the mining areas I'm not quite sure what you mean yet. The intention is you can use the current UI mining tool to mark out the shapes and areas you want to mine. Right now the temptation is just to designate a huge area but a future update will mean that large areas will collapse without pillars/supports in place, which will discourage this kind of behaviour and make players think a bit more about how they're digging.

**Comment by AlexanderEsin** [comment]
> Yep clearing a large area isn't a good approach for sustaining trees for growth in an area, it's more effective to take out strips of a wood and let them grow back in again.

Yes, but to optimise reseeding (granted I'm not sure how the algorithm decides seedlings) you might want to have a seed tree surrounded by clearing to maximise new tree growth. So in a given area, instead of manually selecting strips to chop, you can select the whole rectangle (dotted line in image) and the dwarves will not cut the "protected" trees while clearing the rest (black). The protected trees will reseed the area and eventually you can clear it again.

![Protect trees](https://user-images.githubusercontent.com/15325436/36906098-f3e6a37a-1e2c-11e8-95cc-fb4a97ebd17b.JPG)

I think this would simplify the resource management and would essentially allow the player to create tree farms - that can be walled etc. Of course the benefit of this is dependent on whether natural tree-regrowth will be removed in favour of seeds and planting or just having the dwarves 'grow' trees.

> Although I can see players wanting to not remove bushes that grow fruit while clearing out other ones.

Yes - good point, same concept re: manually clearing "around" resources you want to keep.

In terms of mining, I was thinking of it as a sort of "stencil" - be designating areas you **don't** want the dwarves to mine. You can plan out your internal cave structures using this "protect" feature, then give the dwarves a rectangle to mine and they will automatically leave those rock sections that are protected. Whilst this is simply a different way of skinning the cat, I can see it being much more efficient - consider the following image:

![Mine Blueprint](https://user-images.githubusercontent.com/15325436/36906302-76e78460-1e2d-11e8-83c7-80c657ea784e.jpg)

In the current set up, I would have to use many rectangles / clicks to select the areas I want to excavate and maintain the pillars (in black). With "protect", I could select the four pillars in four movement and then get my dwarves to excavate the whole rectangle (disregarding my stupid entrance). I guess this feels more intuitive to me, especially as you mention the need for cave supports in the future.

I hope this makes more sense, and excuse my hand-drawn diagrams :)

Alex

**Comment by rossturner** [comment]
Love the hand-drawn diagrams! I'm going to leave this open for a while as I mull over it, but for now I'm thinking I'll do something to let the player directly plant trees to avoid the need for this kind of feature.

For the walls, I guess I assumed people would either click and drag out the areas they wanted to mine in the shapes they wanted, or in the case of your diagram, mark out the area then "cancel" the mining on the squares indicated to leave those in place. Same result, different order. I guess that gives the same functionality without adding another option?

**Comment by AlexanderEsin** [comment]
> or in the case of your diagram, mark out the area then "cancel" the mining on the squares indicated to leave those in place.

Absolutely - I'm all for keeping the options as simple and few as possible!

**Comment by rossturner** [comment]
Moved to https://trello.com/c/OFMKpv9S
