### ISSUE TITLE
MacOS - UI scaling

### ISSUE THREAD

**Issue by AlexanderEsin** [RocketJumpTechnology/King-under-the-Mountain-Issue-Tracking#24]
Hi Ross,

Not sure why but the UI (command icons) and the game-speed controls don't scale / render correctly in the Mac version anymore. Running the previous release under identical conditions doesn't have that issue (see side-by-side below).

![screen shot 2018-03-02 at 16 38 35](https://user-images.githubusercontent.com/15325436/36910384-8260df20-1e38-11e8-8c39-06a84fe583ed.png)

It may not be clear from the screenshot - but the UI is much lower resolution, presumably due to its increased size.

Alex

**Comment by rossturner** [comment]
Oh dear, looks like I need to tinker around with the scaling quite a bit more. Based on the size of that screenshot (could you let me know what resolution it is?) I'd expect it to be smaller, not larger like that. UI coding is a pain :)

Reminds me of a tweet from a game developer pointing out that Mac issues accounted for 70% of support issues, but 3% of sales, so he's not supporting it in the future! I'm hoping that Java avoids it getting quite that bad for me.

Thanks as ever for raising these Alex!

**Comment by AlexanderEsin** [comment]
The two instances are actually running side-by-side in non-fullscreen mode. Hard to say exactly what the resolution is, but I guess it's not as simple as "whatever worked for the previous release"?

I can take a screenshot fullscreen at my 2560x1440 resolution if you want, but in the meantime I'm attaching an _overlay_, if you will. On top is the old (fixed) release, directly below is the new release. The icons are as close as I can get them. The windows are as close to the same size as I can get them by eye.

![UI Scaling MacOS](https://user-images.githubusercontent.com/15325436/36912827-e9b411cc-1e3f-11e8-99df-d87e506cd13d.png)

You can't see the speed UI in this, but I suppose it will need to be scaled by the same factor as the icons.

> Reminds me of a tweet from a game developer pointing out that Mac issues accounted for 70% of support issues, but 3% of sales, so he's not supporting it in the future! I'm hoping that Java avoids it getting quite that bad for me.

Yeah - it's not optimal. Even 3% of sales sounds generous :) I'm only really running this on Mac because that's what I have at work and ... well ... this beats work.

**Comment by rossturner** [comment]
There's now a UI scaling option in the all-new options menu! UI scaling is on the main screen in the current version but the current dev version includes a fully-fledged (actually very basic-looking) options screen.
